---
abstract: 'DEPRECATED - An RT extension to perform S/MIME encryption and decryption for mail RT sends'
author:
  - 'Jesse Vincent  C<< <jesse@bestpractical.com> >>'
  - 'Jesse Vincent <jesse@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Crypt-SMIME
no_index:
  directory:
    - etc
    - html
    - inc
    - t
requires:
  File::Temp: 0
  Hook::LexWrap: 0
  IPC::Run3: 0
  String::ShellQuote: 0
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.23
