--- 
abstract: An RT extension to perform S/MIME encryption and decryption for mail RT sends
author: 
  - Jesse Vincent <jesse@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RT-Crypt-SMIME
no_index: 
  directory: 
    - etc
    - html
    - inc
    - t
requires: 
  File::Temp: 0
  Hook::LexWrap: 0
  IPC::Run3: 0
  String::ShellQuote: 0
  Test::More: 0
version: 0.22
